filename:
  "Transactions.xlsx"

word_search:
  top: Sale Date
  left: Sale Date
  bot:
    - For more details
    - BDO Unibank, Inc. is regulated by
  right: Amount
  statement_dt: Statement Date
  payment_due_dt: Payment Due Date
