TableBox:
  - 

DateBox:
  statement_box:
    - 
  payment_due_box:
    - 

RectSearch:
  top:
    - Sale Date
  left:
    - Sale Date
  bot:
    - For more details
    - BDO Unibank, Inc. is regulated by
  right:
    - Amount

DateSearch:
  statement_dt: Statement Date
  payment_due_dt: Payment Due Date
